/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Chunk = Uint8Array;
export interface File {
  'status' : UploadStatus,
  'created' : bigint,
  'owner' : UserId,
  'shareToken' : [] | [string],
  'mimeType' : string,
  'totalSize' : bigint,
  'filename' : string,
  'fileId' : FileId,
  'totalChunks' : bigint,
}
export type FileId = number;
export type Role = { 'Staff' : null } |
  { 'Client' : null } |
  { 'Master' : null };
export type SessionToken = string;
export type UploadStatus = { 'Complete' : null } |
  { 'Pending' : null };
export type UserId = number;
export interface UserProfile {
  'id' : UserId,
  'username' : string,
  'role' : Role,
  'quota' : bigint,
  'gbAllocation' : bigint,
  'usedBytes' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createUser' : ActorMethod<[SessionToken, string, string, Role], UserId>,
  'deleteFile' : ActorMethod<[SessionToken, FileId], undefined>,
  'deleteUser' : ActorMethod<[SessionToken, UserId], undefined>,
  'downloadFile' : ActorMethod<
    [FileId, [] | [SessionToken], [] | [string]],
    { 'data' : Uint8Array, 'mimeType' : string, 'filename' : string }
  >,
  'finalizeUpload' : ActorMethod<[SessionToken, FileId], undefined>,
  'generateShareLink' : ActorMethod<[SessionToken, FileId], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMe' : ActorMethod<[SessionToken], UserProfile>,
  'getMyStorageStats' : ActorMethod<
    [SessionToken],
    { 'quota' : bigint, 'gbAllocation' : bigint, 'usedBytes' : bigint }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStorageStats' : ActorMethod<
    [SessionToken, UserId],
    { 'quota' : bigint, 'gbAllocation' : bigint, 'usedBytes' : bigint }
  >,
  'initUpload' : ActorMethod<
    [SessionToken, string, string, bigint, bigint],
    FileId
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listFiles' : ActorMethod<[SessionToken], Array<File>>,
  'listUsers' : ActorMethod<[SessionToken], Array<UserProfile>>,
  'login' : ActorMethod<[string, string], SessionToken>,
  'logout' : ActorMethod<[SessionToken], undefined>,
  'registerUser' : ActorMethod<[string, string], UserId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateUserGbLimit' : ActorMethod<[SessionToken, UserId, bigint], undefined>,
  'updateUserRole' : ActorMethod<[SessionToken, UserId, Role], undefined>,
  'uploadChunk' : ActorMethod<[SessionToken, FileId, bigint, Chunk], bigint>,
  'validateSession' : ActorMethod<
    [SessionToken],
    { 'username' : string, 'role' : Role }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];