/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SessionToken = IDL.Text;
export const Role = IDL.Variant({
  'Staff' : IDL.Null,
  'Client' : IDL.Null,
  'Master' : IDL.Null,
});
export const UserId = IDL.Nat32;
export const FileId = IDL.Nat32;
export const UserProfile = IDL.Record({
  'id' : UserId,
  'username' : IDL.Text,
  'role' : Role,
  'quota' : IDL.Nat,
  'gbAllocation' : IDL.Nat,
  'usedBytes' : IDL.Nat,
});
export const UploadStatus = IDL.Variant({
  'Complete' : IDL.Null,
  'Pending' : IDL.Null,
});
export const File = IDL.Record({
  'status' : UploadStatus,
  'created' : IDL.Int,
  'owner' : UserId,
  'shareToken' : IDL.Opt(IDL.Text),
  'mimeType' : IDL.Text,
  'totalSize' : IDL.Nat,
  'filename' : IDL.Text,
  'fileId' : FileId,
  'totalChunks' : IDL.Nat,
});
export const Chunk = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createUser' : IDL.Func(
      [SessionToken, IDL.Text, IDL.Text, Role],
      [UserId],
      [],
    ),
  'deleteFile' : IDL.Func([SessionToken, FileId], [], []),
  'deleteUser' : IDL.Func([SessionToken, UserId], [], []),
  'downloadFile' : IDL.Func(
      [FileId, IDL.Opt(SessionToken), IDL.Opt(IDL.Text)],
      [
        IDL.Record({
          'data' : IDL.Vec(IDL.Nat8),
          'mimeType' : IDL.Text,
          'filename' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'finalizeUpload' : IDL.Func([SessionToken, FileId], [], []),
  'generateShareLink' : IDL.Func([SessionToken, FileId], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMe' : IDL.Func([SessionToken], [UserProfile], ['query']),
  'getMyStorageStats' : IDL.Func(
      [SessionToken],
      [
        IDL.Record({
          'quota' : IDL.Nat,
          'gbAllocation' : IDL.Nat,
          'usedBytes' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStorageStats' : IDL.Func(
      [SessionToken, UserId],
      [
        IDL.Record({
          'quota' : IDL.Nat,
          'gbAllocation' : IDL.Nat,
          'usedBytes' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'initUpload' : IDL.Func(
      [SessionToken, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [FileId],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listFiles' : IDL.Func([SessionToken], [IDL.Vec(File)], ['query']),
  'listUsers' : IDL.Func([SessionToken], [IDL.Vec(UserProfile)], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [SessionToken], []),
  'logout' : IDL.Func([SessionToken], [], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [UserId], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateUserGbLimit' : IDL.Func([SessionToken, UserId, IDL.Nat], [], []),
  'updateUserRole' : IDL.Func([SessionToken, UserId, Role], [], []),
  'uploadChunk' : IDL.Func(
      [SessionToken, FileId, IDL.Nat, Chunk],
      [IDL.Nat],
      [],
    ),
  'validateSession' : IDL.Func(
      [SessionToken],
      [IDL.Record({ 'username' : IDL.Text, 'role' : Role })],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SessionToken = IDL.Text;
  const Role = IDL.Variant({
    'Staff' : IDL.Null,
    'Client' : IDL.Null,
    'Master' : IDL.Null,
  });
  const UserId = IDL.Nat32;
  const FileId = IDL.Nat32;
  const UserProfile = IDL.Record({
    'id' : UserId,
    'username' : IDL.Text,
    'role' : Role,
    'quota' : IDL.Nat,
    'gbAllocation' : IDL.Nat,
    'usedBytes' : IDL.Nat,
  });
  const UploadStatus = IDL.Variant({
    'Complete' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const File = IDL.Record({
    'status' : UploadStatus,
    'created' : IDL.Int,
    'owner' : UserId,
    'shareToken' : IDL.Opt(IDL.Text),
    'mimeType' : IDL.Text,
    'totalSize' : IDL.Nat,
    'filename' : IDL.Text,
    'fileId' : FileId,
    'totalChunks' : IDL.Nat,
  });
  const Chunk = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createUser' : IDL.Func(
        [SessionToken, IDL.Text, IDL.Text, Role],
        [UserId],
        [],
      ),
    'deleteFile' : IDL.Func([SessionToken, FileId], [], []),
    'deleteUser' : IDL.Func([SessionToken, UserId], [], []),
    'downloadFile' : IDL.Func(
        [FileId, IDL.Opt(SessionToken), IDL.Opt(IDL.Text)],
        [
          IDL.Record({
            'data' : IDL.Vec(IDL.Nat8),
            'mimeType' : IDL.Text,
            'filename' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'finalizeUpload' : IDL.Func([SessionToken, FileId], [], []),
    'generateShareLink' : IDL.Func([SessionToken, FileId], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMe' : IDL.Func([SessionToken], [UserProfile], ['query']),
    'getMyStorageStats' : IDL.Func(
        [SessionToken],
        [
          IDL.Record({
            'quota' : IDL.Nat,
            'gbAllocation' : IDL.Nat,
            'usedBytes' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStorageStats' : IDL.Func(
        [SessionToken, UserId],
        [
          IDL.Record({
            'quota' : IDL.Nat,
            'gbAllocation' : IDL.Nat,
            'usedBytes' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'initUpload' : IDL.Func(
        [SessionToken, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [FileId],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listFiles' : IDL.Func([SessionToken], [IDL.Vec(File)], ['query']),
    'listUsers' : IDL.Func([SessionToken], [IDL.Vec(UserProfile)], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [SessionToken], []),
    'logout' : IDL.Func([SessionToken], [], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [UserId], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateUserGbLimit' : IDL.Func([SessionToken, UserId, IDL.Nat], [], []),
    'updateUserRole' : IDL.Func([SessionToken, UserId, Role], [], []),
    'uploadChunk' : IDL.Func(
        [SessionToken, FileId, IDL.Nat, Chunk],
        [IDL.Nat],
        [],
      ),
    'validateSession' : IDL.Func(
        [SessionToken],
        [IDL.Record({ 'username' : IDL.Text, 'role' : Role })],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };